### PR TITLE
Multiprocess monitoring

### PR DESCRIPTION
**Pull request by joshmoore**
Copy of https://github.com/korfuri/django-prometheus/pull/46 against https://github.com/IDR/django-prometheus for tagging before a production release.

cc: @manics

### CODE REVIEW

**Comment by manics** [comment]
`git diff pr46 pr1`: code is identical, good to merge

**Comment by joshmoore** [comment]
Proposed tag? `1.0.10-IDR1` and/or `1.1.0-IDR1`? (i.e. pre-releases of the next anticipated version with the current release being `1.0.9`)

**Comment by manics** [comment]
`1.0.10-IDR1`?

**Comment by joshmoore** [comment]
https://github.com/IDR/django-prometheus/releases/tag/v1.0.10-IDR1

**Pull request merged**
